exports.English = {
    signIn: 'Sign In',
    username: 'Username',
    password: 'Password',
    tokenSignin: 'Sign in with token',
    nickname: 'Nickname',
    signUp: 'Sign Up',
    signUpSuccessfully: 'You\'ve signed up successfully!',
    notEmpty: 'cannot be empty',
    request: 'want to add you as a friend',
    add: 'Add',
    delete: 'Delete',
    addAFriend: 'Add friend',
    delAFriend: 'Delete friend',
    quit: 'Quit',
    groups: 'Groups',
    strangers: 'Strangers',
    chatrooms: 'Chat rooms',
    friends: 'Friends',
    exceed: 'Please upload a file less than 10M.',
    invalidType: 'Invalid type',
    uploadFileFailed: 'An error occured when uploading a file',
    agree: 'Agree',
    reject: 'Reject',
    send: 'Send',
    notin: 'You are not in the current chat room.',
    sendImageFailed: 'Failed to send image!',
    sendAudioFailed: 'Failed to send audio!',
    sendFileFailed: 'Failed to send file!',
    image: 'Image',
    audio: 'Audio',
    file: 'File',
    location: 'Location',
    video: 'Video',
    cmd: 'Command',
    download: 'Download',
    loading: 'Loading',
    FileLoading: 'Loading...',
    openFile: 'Open File',
    openDir: 'Open Dir',
    noaccount: 'No account',
    signupnow: 'Sign up now',
    joinPublicGroup: 'Join Group',
    createGroup: 'Create Group',
    chooseGroupMember: 'Choose Member',
    selectedLabel: "Selected",
    groupMemberLabel: "Member",
    groupSubject: 'Group Subject',
    groupDescription: 'Group Description',
    groupPermission: 'Group Permission',
    groupMemberPermission: 'Group Member Permission',
    adminGroupMembers: 'Admin Group Members',
    inviteGroupMembers: 'Invite Group Members',
    changeGroupSubject: 'Change Subjec',
    changeGroupDescription: 'Change Description',
    destroyGroup: 'Destroy',
    leaveGroup: 'Leave',
    haveaccount: 'i have account',
    confirm: "confirm",
    cancel: "cancel",
    contact_added: 'Contact added!',
    contact_deleted: 'Contact deleted!',
    addFriendSelfInvalid: 'Can\'t add youself as friend',
    delFriendSelfInvalid: 'Can\'t del youself as friend',
    addFriendRepeat: 'is friend already',
    addToBlackList: 'add to blacklist',
    blacklist: 'Blacklist',
    ShowBlacklist: 'Blacklist',
    groupBlacklist: 'Blacklist',
    showGroupBlacklist: 'Blacklist',
    memberInvite: 'Invite',
    changeGroupInfo: 'Edit group info',
    groupNotification: 'Group Notification',
    last: '',
    nomorethan: 'No more than ',
    reslogatonetime: ' resources login at one time'
};

exports.Chinese = {
    signIn: '登录',
    username: '用户名',
    password: '密码',
    tokenSignin: '使用token登录',
    nickname: '昵称',
    signUp: '注册',
    signUpSuccessfully: '注册成功',
    notEmpty: '不能为空',
    request: '请求添加好友',
    add: '添加',
    delete: '删除',
    addAFriend: '添加好友',
    delAFriend: '删除好友',
    quit: '退出',
    groups: '群组',
    strangers: '陌生人',
    chatrooms: '聊天室',
    friends: '好友',
    exceed: '请上传大小不超过10M的文件',
    invalidType: '不支持此类型',
    uploadFileFailed: '上传文件发生错误',
    agree: '同意',
    reject: '拒绝',
    send: '发送',
    notin: '您不在当前聊天室',
    sendImageFailed: '图片发送失败',
    sendAudioFailed: '发送音频失败',
    sendFileFailed: '文件音频失败',
    image: '图片',
    audio: '音频',
    file: '文件',
    location: '位置',
    video: '视频',
    cmd: '命令消息',
    download: '点击下载',
    loading: '正在加载',
    FileLoading: '正在下载...',
    openFile: '打开文件',
    openDir: '打开文件夹',
    noaccount: '没有账号',
    signupnow: '现在注册',
    joinPublicGroup: '申请加入公开群',
    createGroup: '创建群组',
    chooseGroupMember: '选择成员',
    selectedLabel: "选中",
    groupMemberLabel: "成员",
    groupSubject: '群组名',
    groupDescription: '群组简介',
    groupPermission: '群组权限',
    groupMemberPermission: '成员权限',
    adminGroupMembers: '管理群成员',
    inviteGroupMembers: '邀请群成员',
    changeGroupSubject: '修改群名称',
    changeGroupDescription: '修改群简介',
    destroyGroup: '解散群组',
    leaveGroup: '退出群组',
    haveaccount: '已有账号',
    confirm: "确定",
    cancel: "取消",
    contact_added: '已发送添加请求!',
    contact_deleted: '好友已删除!',
    addFriendSelfInvalid: '不能添加自己为好友',
    delFriendSelfInvalid: '该好友不存在',
    addFriendRepeat: '已经是好友',
    addToBlackList: '加入黑名单',
    blacklist: '好友黑名单',
    ShowBlacklist: '好友黑名单',
    // button
    groupBlacklist: '群组黑名单',
    // title
    showGroupBlacklist: '群组黑名单',
    memberInvite: '邀请好友',
    changeGroupInfo: '修改群信息',
    groupNotification: '群消息',
    last: '',
    nomorethan: '当前最多支持',
    reslogatonetime: '个资源同时登录'
};
