exports.English = {
    signIn: 'Sign In',
    username: 'Username',
    password: 'Password',
    tokenSignin: 'Sign in with token',
    nickname: 'Nickname',
    signUp: 'Sign Up',
    signUpSuccessfully: 'You\'ve signed up successfully!',
    notEmpty: 'cannot be empty',
    request: 'want to add you as a friend',
    add: 'Add',
    delete: 'Delete',
    addAFriend: 'Add friend',
    delAFriend: 'Delete friend',
    quit: 'Quit',
    groups: 'Groups',
    strangers: 'Strangers',
    chatrooms: 'Chat rooms',
    friends: 'Friends',
    exceed: 'Please upload a file less than 10M.',
    invalidType: 'Invalid type',
    uploadFileFailed: 'An error occured when uploading a file',
    agree: 'Agree',
    reject: 'Reject',
    send: 'Send',
    notin: 'You are not in the current chat room.',
    sendImageFailed: 'Failed to send image!',
    sendAudioFailed: 'Failed to send audio!',
    sendFileFailed: 'Failed to send file!',
    image: 'Image',
    audio: 'Audio',
    file: 'File',
    location: 'Location',
    video: 'Video',
    cmd: 'Command',
    download: 'Download',
    noaccount: 'No account',
    signupnow: 'Sign up now',
    haveaccount: 'i have account'
};

exports.Chinese = {
    signIn: '登录',
    username: '用户名',
    password: '密码',
    tokenSignin: '使用token登录',
    nickname: '昵称',
    signUp: '注册',
    signUpSuccessfully: '注册成功',
    notEmpty: '不能为空',
    request: '请求添加好友',
    add: '添加',
    delete: '删除',
    addAFriend: '添加好友',
    delAFriend: '删除好友',
    quit: '退出',
    groups: '群组',
    strangers: '陌生人',
    chatrooms: '聊天室',
    friends: '好友',
    exceed: '请上传大小不超过10M的文件',
    invalidType: '不支持此类型',
    uploadFileFailed: '上传文件发生错误',
    agree: '同意',
    reject: '拒绝',
    send: '发送',
    notin: '您不在当前聊天室',
    sendImageFailed: '图片发送失败',
    sendAudioFailed: '发送音频失败',
    sendFileFailed: '文件音频失败',
    image: '图片',
    audio: '音频',
    file: '文件',
    location: '位置',
    video: '视频',
    cmd: '命令消息',
    download: '点击下载',
    noaccount: '没有账号',
    signupnow: '现在注册',
    haveaccount: '已有账号'
};
